name: CI

on: ["push", "pull_request"]

jobs:
  ci:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.12.1

    steps:
      - uses: actions/checkout@v2

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            ~/.mix
            deps
            _build
          key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}

      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile

      - name: Compile
        env:
          MIX_ENV: test
        run: mix compile --warnings-as-errors

      - name: Lint format
        run: mix format --check-formatted

      - name: Lint xref
        run: |
          CYCLES=$(mix xref graph --format=cycles)

          if echo "$CYCLES" | grep "No cycles found"; then
            true
          else
            echo "Found module dependency cycle:"
            echo "$CYCLES"
            exit 1
          fi

      - name: Test
        run: mix test
